export const defaultNeighborhoods = [
  "Barra da Tijuca",
  "Botafogo",
  "Cafubá",
  "Camboinhas",
  "Camorim",
  "Catete",
  "Charitas",
  "Copacabana",
  "Cosme Velho",
  "Fátima",
  "Flamengo",
  "Gávea",
  "Gloria",
  "Grumari",
  "Humaitá",
  "Icaraí",
  "Itacoatiara",
  "Itaipu",
  "Itanhangá",
  "Ipanema",
  "Jardim Botânico",
  "Joá",
  "Lagoa",
  "Laranjeiras",
  "Leblon",
  "Leme",
  "Piratininga",
  "Recreio dos Bandeirantes",
  "Santa Rosa",
  "São Conrado",
  "São Francisco",
  "Tijuca",
  "Urca",
  "Vargem Grande",
  "Vargem Pequena",
] as const;

export const propertyTypes = [
  "Apartamento",
  "Casa",
  "Cobertura",
  "Kitnet",
  "Loft",
  "Studio",
  "Flat",
  "Sobrado",
  "Duplex",
  "Triplex",
] as const;

export const releaseStatus = ["Na planta", "Em construção", "Recém entregue"] as const;

export const cities = ["Rio de Janeiro", "Niterói"] as const;

export const statusProperty = ["Venda", "Aluguel"] as const;

export const defaultFeatures = [
  "Piscina",
  "Piscina Infantil",
  "Piscina Aquecida",
  "Academia",
  "Salão de Festas",
  "Espaço Gourmet",
  "Churrasqueira",
  "Sauna",
  "Quadra Poliesportiva",
  "Quadra de Tênis",
  "Playground",
  "Brinquedoteca",
  "Coworking",
  "Sala de Reunião",
  "Portaria 24h",
  "Controle de Acesso",
  "Câmeras de Segurança",
  "Elevador Social",
  "Elevador de Serviço",
  "Gerador de Energia",
  "Bicicletário",
  "Pet Place",
  "Estacionamento para Visitantes",
  "Rooftop",
  "Lounge",
  "Wi-Fi nas Áreas Comuns",
  "Ar condicionado",
  "Lavanderia",
  "Cozinha equipada",
  "Área de serviço",
] as const;
